#!/usr/bin/env bash

variants=(
	"fabric"
	"architectury"
	"unimined"
)

printf '%s\0' "${variants[@]}" | grep -Fxqz -- "$1" || { echo "Available variants: fabric, architectury, unimined" >&2; exit 1; }

[ "$1" = "unimined" ] && FOLDER_NAME="$1" || FOLDER_NAME="$1-loom"
cd ./upstreams/$FOLDER_NAME && \
find ../../patches/$FOLDER_NAME -name '*.patch' -print0 | sort -z | xargs -0 -n 1 patch -p1 -i
