name: Build and Publish

on:
  push:
    branches:
      - dev/**
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        variant:
          #- "fabric"
          - "architectury"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: null2264/actions/gradle-setup@a4d662095a2f2af1ed24f1228eb6e55b0f9f1f29
        with:
          java: 21
          distro: adopt

      - name: Apply patches
        run: |
          git submodule update --init
          ./apply-patches ${{ matrix.variant }}

      - name: Build
        run: |
          cd upstreams/${{ matrix.variant }}-loom
          ./gradlew build -x test

      - name: Publish
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd upstreams/${{ matrix.variant }}-loom
          ./gradlew publish -x test
        env:
          MAVEN_URL: 'https://maven.aap.my.id/'
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
