name: Tests

on:
  push:
    branches:
      - dev/**
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        variant:
          #- "fabric"
          - "architectury"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: null2264/actions/gradle-setup@a4d662095a2f2af1ed24f1228eb6e55b0f9f1f29
        with:
          java: 17
          distro: adopt

      - name: Apply patches
        run: |
          git submodule update --init
          ./apply-patches ${{ matrix.variant }}

      - name: Build and test
        run: |
          cd upstreams/${{ matrix.variant }}-loom
          ./gradlew build

      - name: Publish test report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'upstreams/**/build/test-results/test/TEST-*.xml'
